name: Generate ISO
description: Creates an ISO for installing an OSTree container to a system

inputs:
  arch:
    description: Architecture for image to build
    default: x86_64
  image-name:
    description: Name of the source container image
    required: true
  version:
    description: Fedora version of installer to build
    required: true
  image-repo:
    description: Repository of the source container image
    required: true
  image-tag:
    description: Tag of the source container image
    required: true
  use-web-installer:
    description: Enable Anaconda web installer
    default: false

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - sh -c
    - make output/${{ inputs.image-name }}-${{ inputs.image-tag}}.iso ARCH=${{ inputs.arch }} VERSION=${{ inputs.version }} IMAGE_REPO=${{ inputs.image-repo }} IMAGE_NAME=${{ inputs.image-name }} IMAGE_TAG=${{ inputs.image-tag }} USE_WEB_INSTALLER=${{ inputs.use-web-installer }}'
