name: Generate ISO
description: Creates an ISO for installing an OSTree container to a system

inputs:
  arch:
    description: Architecture for image to build
    default: x86_64
  image-name:
    description: Name of the source container image
    required: true
  version:
    description: Fedora version of installer to build
    required: true
  image-repo:
    description: Repository of the source container image
    required: true
  image-tag:
    description: Tag of the source container image
    required: true
  use-web-installer:
    description: Enable Anaconda web installer
    default: false

runs:
  using: composite
  steps:
    - name: Build image
      shell: bash
      run: |
        docker build -t isogenerator:local -f Dockerfile .

    - name: Download image
      shell: bash
      run: |
        docker run --rm --privileged \
          --volume .:/isogenerator/output \
          -e IMAGE_NAME="${{ inputs.image-name }}" \
          -e IMAGE_TAG="${{ inputs.image-tag }}" \
          -e ARCH="${{ inputs.arch }}" \
          -e VERSION="${{ inputs.version }}" \
          -e IMAGE_REPO="${{ inputs.image-repo }}" \
          -e USE_WEB_INSTALLER="${{ inputs.use-web-installer }}" \
          isogenerator:local \
          bash -c 'make container/"$IMAGE_NAME"-"$IMAGE_TAG" ARCH="$ARCH" VERSION="$VERSION" IMAGE_REPO="$IMAGE_REPO" IMAGE_TAG="$IMAGE_TAG" USE_WEB_INSTALLER="$USE_WEB_INSTALLER"'
