name: ISO Generator CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        installer: [web, legacy]
        boot: [secureboot, ]
    env:
      FEDORA_VERSION: 39
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Run Action
        uses: ./
        id: run
        with:
          image-name: lumina
          image-repo: ghcr.io/rsturla/eternal-linux
          image-tag: ${{ env.FEDORA_VERSION }}
          use-web-installer: ${{ matrix.installer == 'web' && 'true' || 'false' }}
          version: ${{ env.FEDORA_VERSION }}
          arch: x86_64
          secureboot-key-url: ${{ matrix.boot == 'secureboot' && 'https://raw.githubusercontent.com/rsturla/eternal-main/main/files/usr/etc/pki/containers/eternal-linux.pub' }}
          secureboot-password: ${{ matrix.boot == 'secureboot' && 'eternal' }}

      - name: Upload ISO
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: lumina-${{ env.FEDORA_VERSION }}-x86_64-${{ matrix.installer }}${{ matrix.boot == 'secureboot' && '-secureboot' }}-iso
          path: |
            ${{ steps.run.outputs.iso-path }}
            ${{ steps.run.outputs.checksum-path }}
          retention-days: 5
