name: ISO Generator CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        installer: [web, legacy]
        boot: [secureboot, insecure]
        image-tag: [39, 39-nvidia]
    env:
      SECUREBOOT_KEY_URL: 'https://github.com/rsturla/akmods/raw/main/_certs/public_key.der'
      FEDORA_VERSION: 39
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Run Action
        uses: ./
        id: run
        with:
          image-name: lumina
          image-repo: ghcr.io/rsturla/eternal-linux
          image-tag: ${{ matrix.image-tag }}
          use-web-installer: ${{ matrix.installer == 'web' && 'true' || 'false' }}
          arch: x86_64
          fedora-version: ${{ env.FEDORA_VERSION }}
          secureboot-key-url: ${{ matrix.boot == 'secureboot' && format('{0}', env.SECUREBOOT_KEY_URL) || '' }}
          secureboot-password: ${{ matrix.boot == 'secureboot' && 'eternal' || '' }}

      - name: Upload ISO
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: lumina-${{ matrix.image-tag }}-x86_64-${{ matrix.installer }}${{ matrix.boot == 'secureboot' && '-secureboot' || '' }}-iso
          path: |
            ${{ steps.run.outputs.iso-path }}
            ${{ steps.run.outputs.checksum-path }}
          retention-days: 5
